API: Added NodeIteratorUtil, ImageRenderer, PublishingUtil, Utils, ImageScaler
sitevision/sitevision-apps pull request #31
Opened 2021-09-15 13:10 UTC by kling90

Added a couple of more API:s I've used in the last couple of weeks.

Not sure how to handle Utils since it can be used to get almost anything, but that would mean we have to write interface definitions for everything obtainable through Utils, that would lead to alot of duplication of documentation.
The primary way of should be to import the API:s and not getting them through Utils?

I've only added getImageScaler to Utils for now since it's the only way to get an instance of that API, I think?

2021-09-16 06:12 UTC, albinohrn commented
I think you're correct in saying that the primary way should be to import the the API:s. However some of the API:s are stateful and importing them could lead to weird/unexpected behaviour.  That is because these external imports will be hoisted and only imported once. And if you're using them in multiple places of your app, you will have a shared instance of this stateful API. This is why we in our linter warns when importing stateful API:s.

You can get around this by using utils though, there you will get a new instance each time you're calling `utils.getImageRenderer()` for instance.

To summarize `getImageScaler` should be acquired through utils and so should `ImageRenderer` (and all other API:s ending in **renderer**).

2021-09-16 06:20 UTC, albinohrn commented
Just to be clear. I don't mean that you have to add all the other renderers now! :)

2021-09-16 06:32 UTC, kling90 commented
Ah of course 😄 
When something is marked as "Requireable" in the docs I've alwasy assumed that's the way to import it. 
But it makes sense to go through Utils when talking about renderers,

I'll add ImageRenderer to Utils as well since I've added docs for that one already.

2021-09-16 07:49 UTC, albinohrn requested changes

2021-09-16 07:49 UTC, albinohrn commented on packages/api/src/server/Utils/index.js
> +  getImageScaler() {},
Missing `getImageRenderer() {},`

2021-09-16 07:49 UTC, albinohrn commented on packages/api/src/server/ImageRenderer/index.d.ts
> +declare namespace imageRenderer {
In order to help prevent others from importing this API I think we should remove the `namespace`.

2021-09-16 08:08 UTC, kling90 commented on packages/api/src/server/ImageRenderer/index.d.ts
> +declare namespace imageRenderer {
Agreed, should "non importable interfaces" be placed in another structure?
When removing the index.js the import is unresolvable (as it should be), but since the ImageRenderer is in the server folder it's still listed when writing the import, same with ImageScaler.

![image](https://user-images.githubusercontent.com/5382014/133574856-74eb171d-14a2-4a24-8aa2-03a95a719dbf.png)

![image](https://user-images.githubusercontent.com/5382014/133575030-066a77ee-3830-4df6-be21-6b5222b3f174.png)

2021-09-17 11:20 UTC, albinohrn commented on packages/api/src/server/ImageRenderer/index.d.ts
> +declare namespace imageRenderer {
Yeah, that might be a good idea. But then the favorite issue of any developer arises - naming! :D 

I would go with a folder names stateful where we could put all of these APIs.

2021-09-20 14:36 UTC, kling90 commented on packages/api/src/server/ImageRenderer/index.d.ts
> +declare namespace imageRenderer {
> There are only two hard things in Computer Science: cache invalidation and naming things.

Where to put the `stateful` folder? Directly under `./src` or in `./src/server`?
Either way it'll still be a suggestion when writing the import path, but builtins are also appearing even though they're not importable. Maybe I'm just overthinking 😄

2021-09-20 14:56 UTC, albinohrn commented on packages/api/src/server/ImageRenderer/index.d.ts
> +declare namespace imageRenderer {
Maybe we're both overthinking this. 😅 I'm back to keeping them in their "correct" place(`./src/server/ImageRenderer`). Then at least it is possible to import them although you'll get a lint warning. If you'd try to import from `stateful` it would break.

But I think we should document them as an interface that you acquire through `utils.get...`.

2021-09-21 05:46 UTC, kling90 commented on packages/api/src/server/ImageRenderer/index.d.ts
> +declare namespace imageRenderer {
Should that be documented here? Or on developer.sitevision.se? 

It already says in the java docs that you should get it from Utils, 
https://developer.sitevision.se/webdav/files/apidocs/senselogic/sitevision/api/render/ImageRenderer.html

But I'm guilty of seeing `@Requireable(value="ImageRenderer")` and thinking "Oh I'll import it directly then!" 😅

2021-09-22 06:27 UTC, albinohrn commented on packages/api/src/server/ImageRenderer/index.d.ts
> +declare namespace imageRenderer {
We'll add more info to the lint warning I think. It'll still work in most cases, but will act weird in some. :)

2021-09-22 06:28 UTC, albinohrn approved these changes

2021-09-22 08:15 UTC, merged