support headless.js and added terser option
sitevision/sitevision-apps pull request #59
Opened 2022-06-20 12:03 UTC by robinlagren

- added headless.js entry
- build to ecma 5 for serverside scripts

2022-06-20 12:06 UTC, robinlagren commented
Namnbytet på config-filen (webpack.config.server-standalone-entry.js) kan säkerligen diskuteras.

2022-06-20 16:00 UTC, albinohrn requested changes

2022-06-20 16:00 UTC, albinohrn commented on packages/sitevision-scripts/config/webpack/webpack.config.server-standalone-entry.js
> +    filename: entry.substring(entry.lastIndexOf(path.sep) + 1),
Du kan använda `path.basename(path[, ext])` här istället. Lär mer [här](https://nodejs.org/api/path.html#pathbasenamepath-ext)

2022-06-21 14:16 UTC, albinohrn approved these changes

2022-06-21 14:17 UTC, merged